// used for [PinnedTable]
// [PinnedTable] id equals to category or custom page id
// category IDs are auto generated by Isar
//! CHANGE IT WITH CAUTION
import 'package:flutter_notes_app/core/types/tabs.dart';

const int allNotesPageId = 9786589254165548;
const int favoriteNotesPageId = 9998754229564522;

// HOME TABS
const List<(String, Tabs)> homeTabs = [
  ('All Notes', Tabs.allNotes),
  ('Favorite Notes', Tabs.favoriteNotes),
  ('Quick Notes', Tabs.quickNotes),
];
