// used for [PinnedTable]
// [PinnedTable] id equals to category or custom page id
// category IDs are auto generated by Isar
//! CHANGE IT WITH CAUTION
const int allNotesPageId = 9786589254165548;
const int favoriteNotesPageId = 9998754229564522;
